### ISSUE TITLE
comentarios

### ISSUE THREAD

**Issue by gastonprieto** [ElDieguii/dds#1]
Ojo que buffer significa otra cosa: https://www.techopedia.com/definition/2759/buffer, lo que modelas se parece mas a una cache

https://github.com/ElDieguii/dds/blob/010e081b5341e8fe83de64615411ee9e8d8d0802/QueMePongo/Tercer_Iteracion/queMePongo_pseudocodigo.java#L18
Aunque estes en pseudocodigo podes pensarlo mas objetoso, como:
horarioProximo = Date.now().addHours(12)

https://github.com/ElDieguii/dds/blob/010e081b5341e8fe83de64615411ee9e8d8d0802/QueMePongo/Tercer_Iteracion/queMePongo_pseudocodigo.java#L6
Si el objeto bufferclima, no necesita esto como dependencia, porque funciona sin estas dos componentes no hace falta que los pongas en el constructor.

Buenisimo que definiste la interfaz ServicioClima. Peroo... no podías tocar la clase AccuWeatherAPI porque es un componente externo, entonces no podes modificar su diseño.

La clase  CondicionesClimaticas si va a necesitar siempre el clima tal vez te convenga tenerlo como atributo en vez de pasarselo siempre, lo cual te evita que distintos componentes se evitan conseguir dicha dependencia y solo el que lo instancie se lo inyecta en el constructor.

Validaciones parece ser una clase generica de validaciones, para que tenga el mensaje categoriaNoInconsistente, podrias delegarselo a la prenda tal vez, prenda.validarUsoEn(unaCategoria)

cuando estas haciendo un pseudocodigo para explicar un diseño no hace falta que muestres como se hacen las subclases.

Trataria de tener un componente que transforme de la interfaz fea de accuweather a una interfaz de objetos y despues otro objeto que tenga esa logica de la cache. fijate que en tu solucion no mostras como haces esa coversion

**Comment by vivona-diego** [comment]
Gracias por el feedback Gasti!!Mañana después de clase hago las correcciones.El 21 may. 2020 0:40, Gaston Prieto <notifications@github.com> escribió:

Ojo que buffer significa otra cosa: https://www.techopedia.com/definition/2759/buffer, lo que modelas se parece mas a una cache

https://github.com/ElDieguii/dds/blob/010e081b5341e8fe83de64615411ee9e8d8d0802/QueMePongo/Tercer_Iteracion/queMePongo_pseudocodigo.java#L18

Aunque estes en pseudocodigo podes pensarlo mas objetoso, como:

horarioProximo = Date.now().addHours(12)

https://github.com/ElDieguii/dds/blob/010e081b5341e8fe83de64615411ee9e8d8d0802/QueMePongo/Tercer_Iteracion/queMePongo_pseudocodigo.java#L6

Si el objeto bufferclima, no necesita esto como dependencia, porque funciona sin estas dos componentes no hace falta que los pongas en el constructor.

Buenisimo que definiste la interfaz ServicioClima. Peroo... no podías tocar la clase AccuWeatherAPI porque es un componente externo, entonces no podes modificar su diseño.

La clase  CondicionesClimaticas si va a necesitar siempre el clima tal vez te convenga tenerlo como atributo en vez de pasarselo siempre, lo cual te evita que distintos componentes se evitan conseguir dicha dependencia y solo el que lo instancie se lo inyecta en el constructor.

Validaciones parece ser una clase generica de validaciones, para que tenga el mensaje categoriaNoInconsistente, podrias delegarselo a la prenda tal vez, prenda.validarUsoEn(unaCategoria)

cuando estas haciendo un pseudocodigo para explicar un diseño no hace falta que muestres como se hacen las subclases.

Trataria de tener un componente que transforme de la interfaz fea de accuweather a una interfaz de objetos y despues otro objeto que tenga esa logica de la cache. fijate que en tu solucion no mostras como haces esa coversion
